### ISSUE TITLE
Bot Telegram non mi scrive

### ISSUE THREAD

**Issue by matjack1** [madbob/torinotechscene#15]
Ciao, l'ultimo messaggio che ho ricevuto dal bot di Telegram risale al 22 giugno, come mai?

Posso aiutare? Non ho trovato codice in questo repo.

**Comment by madbob** [comment]
Lo aveva allestito @marcofromsicily usando un servizio terzo, bisognerebbe sentire lui.

**Comment by marcofromsicily** [comment]
Ciao, ho resettato il bot.
Spero che basti per farlo riprendere a funzionare.
Il bot è stato creato con https://manybot.io/ ed ho impostato una funzione che semplicemente importa i contenuti dal feed rss.
Per sicurezza ho passato in privato il token del bot a madbob, che può utilizzarlo come vuole per il futuro.

**Comment by matjack1** [comment]
Grande, grazie!

Al primo messaggio che ricevo chiudo l'issue.

**Comment by matjack1** [comment]
Funziona!
