### ISSUE TITLE
Differenza con TorinoTech?

### ISSUE THREAD

**Issue by gmacario** [madbob/torinotechscene#2]
Ciao,

Ho scoperto solo oggi http://torinotechscene.it/ e il relativo progetto GitHub https://github.com/madbob/torinotechscene.

Da alcuni giorni conoscevo (e ho gia' fatto una PR) il sito http://torinotech.it/ e relativo progetto GitHub https://github.com/TorinoTech/torinotech.github.io

Entrambe mi sembrano lodevoli iniziative, ma qualcuno e' in grado di spiegarmi la differenza di contenuti e "dove-pubblicare-cosa"?

See also: https://github.com/TorinoTech/torinotech.github.io/issues/11

**Comment by madbob** [comment]
Differenza dei contenuti: idealmente sono gli stessi, benché su TorinoTechScene personalmente prediliga gli eventi automaticamente importati da gruppi semi-permanenti. Sembra che alcune realtà siano trattate su TorinoTechScene ma non su TorinoTech (cfr. i CoderDojo) e viceversa, ma tendenzialmente entrambe le piattaforme accolgono spontanee richieste di pubblicazione per mezzo di pull request.

Dove pubblicare cosa: su TorinoTech non so; su TorinoTechScene è possibile pubblicare nuovi eventi creando un file nella cartella `_posts` ([qui un esempio](https://raw.githubusercontent.com/madbob/torinotechscene/gh-pages/_posts/2015-12-06-esempio.markdown)). Oppure, meglio ancora, è possibile [segnalare un gruppo](https://github.com/madbob/torinotechscene/blob/gh-pages/_data/groups.yml) indicando come riferimento una pagina Facebook, Meetup o Eventbrite, da cui i contenuti saranno automaticamente importati.

Nota a margine in merito alla scelta dell'importazione automatica, che forse è la differenza tecnica fondamentale tra i due progetti: per quanto possa essere un comportamento opinabile, in quanto potenziale vettore di errori e segnalazioni non attinenti, nel corso della mia esperienza come co-maintainer della [mappa nazionale dei Linux Users Groups](http://lugmap.linux.it/) ho personalmente avuto modo di constatare che le iniziative di indicizzazione e mappatura (come appunto queste) tendono ad essere nel tempo abbandonate se non adeguatamente supportate da un qualche grado di automazione, in quanto presto o tardi il mantenimento interamente manuale diventa un onere insostenibile. Dunque, di mio, preferisco tollerare qualche occasionale errore che non vedere il progetto "morto" nel giro di un anno o due, come fin troppo spesso accade.
