### ISSUE TITLE
Sito non si aggiorna in automatico

### ISSUE THREAD

**Issue by matjack1** [madbob/torinotechscene#20]
Ciao @madbob, il sito non si aggiorna più in automatico :(

Se vuoi ti do una mano volentieri a capire cosa c'è che non va, guardo volentieri anche sul server se ti va, possiamo sentirci anche via mail

**Comment by madbob** [comment]
Sistemato. Qualche pasticcio durante l'ultimo aggiornamento dei moduli Ruby...
Grazie della segnalazione ;-)
