### ISSUE TITLE
credo si sia rotta la generazione dell'html nel sito

### ISSUE THREAD

**Issue by xrmx** [madbob/torinotechscene#23]
Perchè non ci sono gli eventi che invece sono stati mandati da twitter.

**Comment by madbob** [comment]
Eventi come MERGE-it, Droidcon e Mini Agile Day non figurano affatto tra i files degli eventi. Né mi sembra di vederli su Twitter. MERGE-it l'ho aggiunto io adesso.

**Comment by xrmx** [comment]
Mancano Hacknight 18/1, Torino Open Source Saturday 20/1 e TCS Rust 23/1 che son stati tutti twittati.

Le conf mancano perchè nessuno le ha aggiunte :)

**Comment by madbob** [comment]
??? A me pare che sul sito ci siano - http://torinotechscene.it/

**Comment by xrmx** [comment]
Adesso si!
