### ISSUE TITLE
Sito non si aggiorna

### ISSUE THREAD

**Issue by matjack1** [madbob/torinotechscene#25]
Ciao @madbob il sito non si è aggiornato dalla scorsa settimana :(

Tra l'altro capisco la policy di caricare solo un evento da Meetup (per esempio), ma così gli eventi settimanali sembra sempre che siano estemporanei. Cosa ne dici di caricare gli eventi che sono dal giorno corrente al mese successivo?

Sempre a disposizione se vuoi una mano. Ciao!

**Comment by madbob** [comment]
Boh... Lanciando manualmente l'aggiornamento sul server sembra andare, dovro' studiarmi meglio cosa fa in cron...

Non ho capito l'osservazione sugli eventi settimanali. Se ti riferisci al fatto che sono duplicati, c'e' una proposta di correzione in #24 (anche se non mi convince molto, dovrei riscriverla).

**Comment by matjack1** [comment]
Non pensavo ai duplicati, pensavo agli eventi ricorrenti, che secondo me sarebbe bello far vedere un po' di più. Per esempio tutti gli eventi da qua ad un mese per un feed, non solo un evento per feed. Nel mio caso ad esempio sarebbe bello far vedere tutti i Coding for everyone organizzati da qua a metà febbraio.

**Comment by madbob** [comment]
Magicamente il sito ha ripreso ad aggiornarsi. Forse merito dell'aggiornamento di sistema operato qualche settimana fa.
