### ISSUE TITLE
eventi di troppo e mancanti

### ISSUE THREAD

**Issue by xrmx** [madbob/torinotechscene#35]
C'è in db un evento perpetuo che si aggiorna ogni giorno dal meetup agile che sarebbe simpatico sistemare. Dal loro meetup pare tutto ok https://www.meetup.com/it-IT/Agile-Community-Torino/events/266429803/

Inoltre manca torino hacknight del 21 gennaio: https://www.eventbrite.it/e/biglietti-torino-hacknight-userbase-86541320419 . C'è qualche problema nell'evento?

**Comment by madbob** [comment]
Meetup Agile: non ho capito pero' quale effetto riscontri su questo evento.

Eventbrite Hacknight: hanno [deprecato e soppresso](https://www.eventbrite.com/platform/api#/reference/event-search/list-deprecated/search-events-deprecated) l'API che usavo prima per pescare gli eventi, ho aggiornato lo script usandone [un'altra](https://www.eventbrite.com/platform/api#/reference/event/list/list-events-by-organization) ma mi restituisce sempre una risposta, seppur valida, con un insieme vuoto. Non capisco se manca un qualche parametro o se il comportamento e' proprio voluto, perche' il mio token di autenticazione non e' valido per l'organizzazione richiesta.

**Comment by xrmx** [comment]
Il meetup agile c'è stato il 21 novembre, su Torino tech scene c'è invece
ogni giorno, compreso oggi 24 dicembre.

Il mar 24 dic 2019, 13:56 Roberto Guido <notifications@github.com> ha
scritto:

**Comment by xrmx** [comment]
Sembra che in database abbiamo l'id dell'organizzatore e non dell'organizzazione. Reference https://groups.google.com/forum/#!topic/eventbrite-api/h1OYx6o_qO0
L'id si prende chiamando questa api da un utente dell'organizzaizone:
https://www.eventbriteapi.com/v3/users/me/organizations/

Faccio una PR per i miei gruppi

**Comment by xrmx** [comment]
Ah sembra comunque che si possa fare query solo sulla propria organizzazione :|

**Comment by xrmx** [comment]
In alternativa possiamo pensare di usare i webhook:
https://www.eventbrite.com/platform/docs/webhooks

C'è la possibilità di avere un endpoint da chiamare?

**Comment by madbob** [comment]
Apposto, mi sono riscritto il fetcher Eventbrite per fare scraping. Grazie della segnalazione e delle dritte ;-)
https://github.com/madbob/torinotechscene/commit/69233db0611b65009b0e7a60a3ea99785d2e1e1d
