### ISSUE TITLE
Driver Meetup: rimuovere eventi non piu' esistenti

### ISSUE THREAD

**Issue by madbob** [madbob/torinotechscene#8]
Succede soprattutto con Torino Coding Society, che pubblica dei placeholders su Meetup salvo poi modificarli coi contenuti reali della serata. In questo modo, resta nell'elenco sia il placeholder che l'evento vero. Quando vengono aggiornati i contenuti da Meetup, bisognerebbe non solo aggiungere i nuovi ma anche eliminare i vecchi che non ci sono piu'.

**Comment by matjack1** [comment]
Ogni quanto lanci lo script `updateme.sh`? Perché un fix facile potrebbe essere quello di cancellare tutti i post di Meetup ogni volta che aggiorni. In ogni caso la chiamata a meetup.com la fai sempre (che è la cosa lenta) forse tanto vale cancellare sempre e ricreare?

Se pensi che l'idea abbia senso posso provare a scrivere qualcosa.

**Comment by madbob** [comment]
Il tutto viene aggiornato una volta al di'. Ci mette solo pochi secondi, e anche se ci mettesse dei minuti non cambierebbe molto.
Francamente non so quale potrebbe essere l'approccio piu' conveniente, se eliminare e ricreare oppure introdurre qualche valutazione piu' sofisticata. L'unica cosa che mi perplime, nel primo caso, e' il fatto di non twittare lo stesso evento ogni volta che viene re-importato. La cache degli eventi twittati, gestita da `scripts/post_twitter.php`, dovrebbe evitare questo problema ma qualche verifica non guasterebbe.
